# Generated by Django 4.2.1 on 2023-07-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=20)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('link', models.URLField()),
                ('about', models.TextField()),
            ],
        ),
    ]
