# Generated by Django 4.2.1 on 2023-07-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='difficulty_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='rating',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
