# Generated by Django 4.2.1 on 2023-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_formation_difficulty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date_trans_time', models.DateTimeField(verbose_name='Transaction Date and Time')),
                ('cc_num', models.CharField(max_length=20, verbose_name='Credit Card Number')),
                ('merchant', models.CharField(max_length=100, verbose_name='Merchant')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('first', models.CharField(max_length=50, verbose_name='First Name')),
                ('last', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('street', models.CharField(max_length=200, verbose_name='Street Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zip', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('city_pop', models.IntegerField(verbose_name='City Population')),
                ('job', models.CharField(max_length=100, verbose_name='Job')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('trans_num', models.CharField(max_length=100, verbose_name='Transaction Number')),
                ('unix_time', models.BigIntegerField(verbose_name='Unix Timestamp')),
                ('merch_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Merchant Latitude')),
                ('merch_long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Merchant Longitude')),
                ('is_fraud', models.BooleanField(verbose_name='Is Fraud')),
            ],
        ),
        migrations.AlterField(
            model_name='formation',
            name='about',
            field=models.TextField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='difficulty_level',
            field=models.CharField(max_length=100, verbose_name='Difficulty Level'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='rating',
            field=models.CharField(max_length=100, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='school',
            field=models.CharField(max_length=100, verbose_name='School'),
        ),
    ]
