# Generated by Django 4.2.1 on 2023-07-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_transaction_alter_formation_about_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='fraudTrain',
        ),
    ]
