# Generated by Django 5.2 on 2025-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_transaction_fraudtrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudtrain',
            name='amt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='cc_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='city_pop',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='first',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='is_fraud',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='job',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='last',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='merch_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='merch_long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='merchant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='street',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='trans_date_trans_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='trans_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='unix_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='fraudtrain',
            name='zip',
            field=models.CharField(max_length=20),
        ),
    ]
