# Generated by Django 4.2.1 on 2023-06-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options'),
        ('projects', '0009_enregistrement_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='profile',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
