# Generated by Django 4.2.1 on 2023-06-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_enregistrement_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='idrec',
            field=models.CharField(blank=True, default=0, max_length=300, null=True),
        ),
    ]
