# Generated by Django 4.2.1 on 2023-06-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_enregistrement_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='etat',
            field=models.CharField(default='En attente', max_length=100),
        ),
    ]
