# Generated by Django 4.2.1 on 2023-06-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_enregistrement_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='avis',
            field=models.CharField(blank=True, default=0, max_length=300, null=True),
        ),
    ]
