# Generated by Django 4.2.1 on 2023-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_enregistrement_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='avis',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
